### ISSUE TITLE
DoneJS Overview V3 notes

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/presentations#1]
- [x] - Hide "desktop and mobile apps" as last step, leave as "mind blown" step. (I like consolidating build+deploy into one step too).
- [x] - Bring back the checkered flags and (1/7) type thing.  It's nice to give context.
- [x] - Error in live-reload? ![v3-justin](https://cloud.githubusercontent.com/assets/78602/16060653/83b48ebc-324e-11e6-814a-9d0e2a114a1b.png)
- [x] - Include a video showing what the messages page looks like. _DONEJS-V9:38 0-10 seconds_.
- [x] - Change  "live reload" to "hot module swapping"
- [x] - consider showing the generated Message model code.

**Comment by chasenlehara** [comment]
@justinbmeyer I can’t assign this issue to myself (permissions?) but I’ll work on these updates.

**Comment by chasenlehara** [comment]
I filed an issue for the error in the screenshot: https://github.com/donejs/done-serve/issues/14

**Comment by chasenlehara** [comment]
The updated presentation file is in the company Google Drive at `Presentations/DoneJS/overviews/Quick Start for Meetups (0.9.0)/V5.key`
